name: projeto_sos
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_getit: ^2.0.0
  geolocator: ^12.0.0
  geolocator_android: 4.5.5
  audioplayers: ^6.0.0
  pulsator: ^1.0.0+2
  asyncstate: ^2.1.0
  torch_controller: ^2.0.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/

  